// Knowledge-base article draft (Bead securitycorp-source-4zl.54.1.2).
// Status is intentionally "drafting" — see docs/publication-safety-policy.md.
// This file is NOT wired into lib/knowledge-content.ts; it becomes part of
// the published catalog only after human privacy/technical/publication
// review, per docs/knowledge-base.md.
import type { KnowledgeArticle } from "../knowledge-content.ts";
import type { UniversalSections, GuideModule } from "../knowledge-content-types.ts";

const sections: UniversalSections = {
  executiveSummary: [
    "Automated secrets scanning — regex pattern matching and Shannon-entropy analysis run against source code, commit diffs, and sometimes full repository history — is a necessary control, not a sufficient one. It reliably catches a known-format credential (a cloud provider's access-key prefix, a recognizable API-token shape) sitting in a tracked source file. It was never designed to catch everything a secret can be, or everywhere a secret can end up.",
    "This guide is not an argument against automated secrets scanning; every recommendation here assumes a scanner is already running. It maps where that scanner's coverage actually ends — context-dependent values it can't recognize as secrets, locations it doesn't inspect, and historical exposure it can't undo on its own — and the compensating controls that close the resulting gap instead of asking pattern matching to do something it fundamentally cannot.",
  ],
  whatYouWillLearn: [
    "Why regex- and entropy-based detectors work well for recognizable, high-entropy formats and poorly for context-dependent or low-entropy secrets.",
    "Where secrets end up outside the source tree a scanner is configured to inspect — CI build logs, generated artifacts, container layers, and split config templates — and why those locations are commonly excluded from scan scope.",
    "Why a secret committed and later 'removed' remains exposed in git history until it is explicitly rotated, and why rotation, not removal, is the control that actually closes the exposure.",
    "How to reason about false negatives (a real secret the scanner never flags) separately from false positives (a high-entropy string flagged that isn't a secret), since fixing one does not fix the other.",
    "A repeatable procedure for layering compensating controls — pre-commit gating, secrets-manager externalization, CI log hygiene, and rotation — around a scanner's actual coverage boundary.",
  ],
  intendedAudience: [
    "Developers who rely on an automated secrets scanner (a pre-commit hook, a CI pipeline step, or a hosted platform feature) and want to know what it isn't checking.",
    "Security practitioners designing or reviewing a secrets-detection program who need to reason about coverage gaps, not just tool selection.",
    "Technical leads deciding where to invest next once a scanner is already in place — rotation policy, secrets-manager adoption, log handling — rather than which scanner brand to buy.",
  ],
  prerequisites: [
    "Basic familiarity with git (commits, history, diffs) and a typical CI/CD pipeline (build steps, logs, artifacts).",
    "No lab environment is required — every example in this guide is fictional and descriptive, not a runnable exercise.",
    "Some prior exposure to the idea of a secrets manager or vault (a system that stores and serves credentials on demand) is helpful but not assumed.",
  ],
  problem: [
    "It's easy to point to a green secrets-scanning check and conclude 'this repository has no exposed credentials.' That conclusion is broader than the evidence supports. A passing scan means: no string matching its configured patterns or entropy threshold was found in the locations it inspected. It says nothing about a secret that doesn't match any configured pattern, a secret sitting in a location the scanner never looks at, or a secret that was exposed in the past and technically still is, in history the scanner didn't rescan.",
    "The gap matters because it is asymmetric. A false positive — the scanner flags a high-entropy string that turns out to be a hash or a UUID — costs a few minutes of a developer's attention. A false negative — a real, live credential the scanner never flags — can sit undetected indefinitely, because the signal that would normally surface it is exactly the one that never fires.",
  ],
  threatModel: [
    "Consider a fictional internal build pipeline we'll call the Northwind deployment pipeline: a developer's workstation, a shared git repository at `git.lab.example.com`, a CI runner that builds and tests every push, and a target environment the CI pipeline deploys to.",
    "Relevant failure modes, not adversaries in the traditional sense: (1) a developer commits a config value that is a live credential but doesn't match any configured detection pattern — a low-entropy internal API key, a database connection string using a common driver format; (2) a credential is emitted to a location outside the scanner's configured scope — a CI build log, a generated build artifact, a container image layer, cached dependency output — rather than to a tracked source file; (3) a credential was committed, later 'fixed' by removing it in a subsequent commit, and treated as resolved, while it remains fully readable in git history to anyone with clone or `git log -p` access; (4) a credential is split or templated across multiple files — a config template plus a separately committed values file — such that no single file contains a string that would trip a pattern or entropy check on its own.",
    "Out of scope for this guide: choosing between specific commercial secrets-scanning products, the cryptography behind secrets-manager implementations, and secrets exposure caused by a compromised endpoint or a compromised upstream dependency rather than a detection-coverage gap.",
  ],
  mainContent: [
    "**Pattern matching finds recognizable formats, not secrets.** A regex-based scanner is only as good as its pattern library. It reliably catches values with a distinctive, documented shape — a cloud provider's access-key prefix, a well-known token format — because someone wrote a pattern for that exact shape. It has no way to recognize a secret that doesn't announce itself: an internal API key with no special prefix, a shared service password, a database connection string that looks, to a regex, like any other string of plausible length.",
    "**Entropy analysis finds randomness, not meaning.** Shannon-entropy scanning flags strings that look statistically random, on the working assumption that a real secret is usually high-entropy and ordinary text isn't. That assumption breaks in both directions. A short, low-entropy password or a predictable internal token can sit below the entropy threshold and pass unnoticed; a UUID, a hash, a base64-encoded non-secret blob, or a minified code fragment can sit above it and generate a false positive. Tuning the threshold trades one failure mode for the other — it does not eliminate either.",
    "**Context is exactly what pattern matching lacks.** Whether a given string is a secret often depends on what surrounds it: is this value read from an environment variable at runtime and used to authenticate to something, or is it a fixture value in a test file that was deliberately never valid? A scanner with no semantic understanding of the code treats both identically, which is why detection tooling routinely ships an allowlist mechanism for known-safe fixtures — and why that same mechanism, misused, becomes a way for a real secret to be waved through as a 'known false positive.'",
    "**Scan scope has edges, and secrets don't respect them.** Most secrets-scanning configurations are pointed at the tracked source tree, and often at commit diffs on push rather than the full repository history by default. That leaves several plausible locations outside scope entirely: CI build logs (a debug step that prints an environment variable's value for troubleshooting), generated build artifacts and caches, container image layers, and infrastructure-as-code plan output that can render a value in cleartext. None of these is source code in the sense the scanner was configured to inspect, and each is a real place a credential has ended up.",
    "**A secret 'removed' from the latest commit is not a secret removed.** Deleting a credential in a new commit takes it out of the current file tree; it does not take it out of git history. Anyone with clone access or `git log -p` access can still read the original commit that introduced it. A scanner configured to check only the diff of new pushes will not re-flag it, because as far as that scan is concerned nothing changed for the worse. Treating a follow-up commit as remediation, without rotating the credential, leaves the actual exposure open indefinitely.",
    "**A split or templated secret defeats a single-file check.** A configuration template committed with a placeholder reference, plus a separate environment-specific values file committed elsewhere with the real value substituted in, can each look unremarkable on their own — neither file alone pairs an obvious credential-shaped key name with a suspicious high-entropy string. A scanner that evaluates files independently, rather than the composed configuration that actually reaches the running service, can miss the combination even though each half is individually visible.",
    "**False negatives and false positives require different fixes.** A false positive is a tuning problem: adjust the pattern, extend the allowlist, raise the entropy threshold, and the noise goes down. A false negative is a coverage problem: no amount of tuning the existing rules teaches the scanner about a format or a location it was never told to check. Treating both as 'scanner accuracy' issues to be solved by iterating on the same configuration confuses two different failure modes that need two different fixes.",
    "**Compensating controls close what detection cannot.** Because the coverage gap is structural, not a tuning defect, the fix is architectural: keep the literal secret out of anything a scanner would have to find in the first place. Externalize credentials to a secrets manager referenced by name — for example a config entry that reads `${DB_CREDENTIAL_REF}` rather than a literal value — so there is no live secret sitting in source, configuration, or a build artifact for a scanner to catch or miss. Pair that with pre-commit gating (catching the easy cases before they reach shared history), CI log hygiene (never printing secret-bearing environment variables, even for debugging), and a rotation policy for anything that was ever exposed. Rotation is the control that actually closes an exposure that already happened; detection only tells you one might exist.",
  ],
  validationEvidence: [
    "This guide describes detection-coverage patterns and a review procedure; it does not include a reproduced scanning exercise, a captured scanner run, or a completed assessment of a real pipeline. Its evidence state remains UNVERIFIED — the technical claims are grounded in the cited OWASP, CWE, and tool-documentation references, not in an exercise performed for this article.",
  ],
  limitations: [
    "This guide covers regex- and entropy-based detection generally; it does not evaluate or compare specific commercial secrets-scanning products, nor does it cover machine-learning-based detection approaches in depth.",
    "The fictional Northwind pipeline example is illustrative, not a reference architecture. A real pipeline's scan scope and compensating controls must be derived from its own CI/CD tooling and threat model, not copied from this guide.",
    "This guide does not cover the operational mechanics of purging a secret from git history (history rewriting, force-push coordination, downstream clone invalidation) in detail — treat that as a separate, carefully scoped procedure, and always pair it with credential rotation rather than relying on history rewriting alone.",
  ],
  defensiveRecommendations: [
    "Externalize credentials to a secrets manager referenced by name or path, never embedded by literal value, so there is nothing live for a scanner to find or miss in source, configuration, or build output.",
    "Run secrets scanning at more than one layer — pre-commit locally and again in CI — while accepting that both layers share the same fundamental blind spots and neither substitutes for externalization.",
    "Extend scan scope deliberately to include CI build logs and generated artifacts where feasible, and avoid printing secret-bearing environment variables in build output even for debugging.",
    "Treat 'removed in a later commit' as unresolved until the credential is rotated; a scanner that only checks new diffs will not re-surface history on its own.",
    "Periodically scan full repository history, not only new pushes, since scan-scope decisions made at rollout time silently exclude everything committed before that point.",
    "Maintain a narrow, reviewed allowlist for known-safe fixture values, and treat any addition to it as a change that itself deserves review — an allowlist entry is a permanent way to stop looking at something.",
  ],
  keyTakeaways: [
    "A passing secrets scan means no configured pattern matched in the locations that were scanned — it is not evidence that no secret exists.",
    "False negatives (coverage gaps) and false positives (tuning noise) are different failure modes with different fixes; solving one doesn't solve the other.",
    "Secrets in CI logs, build artifacts, and git history are real exposures that a diff-scoped, source-tree-only scanner routinely misses.",
    "Externalizing credentials to a secrets manager, not tuning the scanner further, is what closes a structural detection gap; rotation, not removal, closes an exposure that already happened.",
  ],
  references: [
    "OWASP Secrets Management Cheat Sheet: https://cheatsheetseries.owasp.org/cheatsheets/Secrets_Management_Cheat_Sheet.html",
    "CWE-798: Use of Hard-coded Credentials: https://cwe.mitre.org/data/definitions/798.html",
    "GitHub Docs — About secret scanning: https://docs.github.com/en/code-security/secret-scanning/about-secret-scanning",
    "TruffleHog (open-source secret scanner): https://github.com/trufflesecurity/trufflehog",
    "Gitleaks (open-source secret scanner): https://github.com/gitleaks/gitleaks",
  ],
  relatedSlugs: ["securing-api-authentication-authorization", "practical-secure-code-review-checklist"],
};

const module_: GuideModule = {
  kind: "guide",
  requirements: [
    "A documented inventory of where automated secrets scanning currently runs (pre-commit, CI, hosted platform feature) and its configured scope (new diffs only vs. full history, which paths and branches are included).",
    "A secrets manager or equivalent externalization mechanism available for credentials the pipeline currently embeds directly.",
    "Access to CI build logs and artifact retention settings sufficient to review what gets printed or cached during a build.",
  ],
  procedure: [
    "List every current secrets-scanning layer and record its actual scope: source tree only or also history, new commits only or full repository, which branches, and whether CI logs or build artifacts are included.",
    "For each layer, identify what it cannot see: known low-entropy or non-standard-format secrets it wouldn't pattern-match, and any location — logs, artifacts, container layers, IaC plan output — outside its configured scope.",
    "Identify every place a credential is currently embedded by literal value — source, configuration file, environment file, IaC template — and replace each with a reference to a secrets manager instead of the value itself.",
    "Review recent CI build logs for any step that prints an environment variable, config value, or debug output that could contain a credential; remove the print statement rather than relying on log access controls alone.",
    "For any credential known or suspected to have been committed at any point in git history, rotate it — do not treat a later commit that deletes the value as sufficient remediation on its own.",
    "Record which coverage gaps are accepted (with a compensating control) versus which remain open, rather than treating 'scanner is green' as a closed item.",
  ],
  validation: [
    "Confirm that a sample of currently externalized credentials resolve correctly from the secrets manager at runtime and that no fallback path silently accepts an embedded literal value instead.",
    "Confirm that a sample of recent CI build logs contain no printed credential value, including in verbose or debug-mode output.",
    "Confirm that any credential rotated after a historical exposure is actually rejected in its old form — the old value no longer authenticates — not merely replaced in configuration while the old value remains valid.",
    "Confirm the secrets-scanning configuration's documented scope matches its actual behavior — for example, that a 'full history' claim is periodically re-verified rather than assumed from initial setup.",
  ],
  rollback: [
    "If externalizing a credential to a secrets manager breaks a legitimate workflow, revert the specific reference and its resolution path rather than reintroducing the literal value, then re-introduce externalization alongside a corrected access policy for the service that failed to resolve it.",
    "If a review finds a currently exposed, live credential, treat the finding as internal-source per the publication-safety policy — do not describe the live weakness publicly, rotate the credential, and route remediation to the responsible team before any public write-up.",
    "If tightening CI log output removes information needed for legitimate debugging, replace the removed value with a redacted or truncated indicator (for example, 'credential present, length N') rather than restoring the literal print statement.",
  ],
};

const diagram: KnowledgeArticle["diagram"] = {
  titleId: "secrets-pipeline-diagram",
  title: "Where secrets travel through a pipeline",
  desc: "A developer's secret moves from a workstation through a pre-commit scan, a git commit, and a CI pipeline scan toward a deployed service that resolves its credentials from a secrets manager. Interactive: switch between the normal path, where the secret is properly externalized to a secrets manager, and the failure path, where a secret printed to an ephemeral CI build log slips past both scan layers — a documented scanner blind spot, not a hypothetical one. Explore each node for details.",
  viewBox: "0 0 940 355",
  failureLabel: "Scanner blind spot",
  caption: "Developer workstation → pre-commit scan → git commit → CI pipeline scan → deployed service, which resolves credentials from a secrets manager at runtime. In the failure path, a secret printed to a CI build log during a debug step is never inspected by either scan layer — a false negative, not a caught finding.",
  motionDuration: 2800,
  mainPacketRoute: { d: "M160,180 H190 M360,180 H390 M540,180 H570 M740,180 H770", length: 120 },
  edges: [
    { id: "workstation-precommit", from: "workstation", to: "precommit", d: "M160,180 H190", length: 30, kind: "main", activeIn: ["normal", "failure"] },
    { id: "precommit-commit", from: "precommit", to: "commit", d: "M360,180 H390", length: 30, kind: "main", activeIn: ["normal", "failure"] },
    { id: "commit-ci", from: "commit", to: "ci", d: "M540,180 H570", length: 30, kind: "main", activeIn: ["normal", "failure"] },
    { id: "ci-deployed", from: "ci", to: "deployed", d: "M740,180 H770", length: 30, kind: "main", activeIn: ["normal"] },
    { id: "deployed-vault", from: "deployed", to: "vault", d: "M845,150 V100", length: 50, kind: "main", activeIn: ["normal"] },
    { id: "ci-buildlog", from: "ci", to: "buildlog", d: "M655,215 V280", length: 65, kind: "failure", activeIn: ["failure"] },
  ],
  nodes: [
    {
      id: "workstation",
      label: "Developer workstation",
      x: 10,
      y: 150,
      w: 150,
      h: 60,
      activeIn: ["normal", "failure"],
      description: "Where a secret is first typed — into a config file, an environment variable, or a debug print statement. Every downstream control depends on what happens to that value between here and the next checkpoint.",
    },
    {
      id: "precommit",
      label: "Pre-commit scan",
      x: 190,
      y: 145,
      w: 170,
      h: 70,
      activeIn: ["normal", "failure"],
      role: "boundary",
      focusableLabel: "Pre-commit scan — first-layer regex/entropy check on staged changes before they reach shared git history",
      description: "First-layer check: a local pre-commit hook runs a regex/entropy scanner against staged changes before they're committed. Effective against a recognizable credential format sitting in a normal source file; it doesn't inspect files outside the commit, generated content, or anything that doesn't match a configured pattern.",
    },
    {
      id: "commit",
      label: "Git commit",
      x: 390,
      y: 150,
      w: 150,
      h: 60,
      activeIn: ["normal", "failure"],
      description: "Once committed, a value is part of git history whether or not a later commit removes it from the current file tree. History remains readable to anyone with clone or log access until it is deliberately rewritten and the credential is rotated.",
    },
    {
      id: "ci",
      label: "CI pipeline scan",
      x: 570,
      y: 145,
      w: 170,
      h: 70,
      activeIn: ["normal", "failure"],
      role: "boundary",
      focusableLabel: "CI pipeline scan — second-layer scan re-checking pushed history and build steps, scoped to source and diffs by default",
      description: "Second-layer check: CI re-scans the pushed history, usually scoped to source files and the diff being pushed. It reliably catches what pre-commit catches. By default it typically does not inspect its own build logs, generated artifacts, or cached layers — exactly where the failure path below shows a secret escaping.",
    },
    {
      id: "deployed",
      label: "Deployed service",
      x: 770,
      y: 150,
      w: 150,
      h: 60,
      activeIn: ["normal"],
      role: "safe",
      description: "The running service resolves its configuration cleanly: every credential is referenced by name or path, never embedded by literal value, so there is nothing for a scanner to have missed at this stage.",
    },
    {
      id: "vault",
      label: "Secrets manager",
      x: 770,
      y: 40,
      w: 150,
      h: 60,
      activeIn: ["normal"],
      role: "safe",
      description: "The secrets manager holds the actual credential value, versioned and access-controlled. Source control, CI configuration, and the deployed artifact each contain only a reference to it — never the value itself.",
    },
    {
      id: "buildlog",
      label: "Build log blind spot",
      x: 555,
      y: 280,
      w: 200,
      h: 60,
      activeIn: ["failure"],
      role: "blocked",
      focusableLabel: "Build log blind spot — a debug step prints a credential to CI log output that neither scan layer inspects",
      description: "A debug or verbose build step prints an environment variable's literal value to the CI log for troubleshooting. Neither the pre-commit scan nor the CI source/diff scan inspects ephemeral log output, and logs are often retained longer, and readable by more people, than the source repository itself. This is a false negative: the scanner reports nothing wrong, and the secret is disclosed anyway.",
    },
  ],
};

export const article: KnowledgeArticle = {
  meta: {
    title: "Secrets Detection: What Automated Scanners Miss",
    slug: "secrets-detection-scanner-limits",
    summary: "Why regex- and entropy-based secrets scanners routinely miss real credentials — and the compensating controls that close the gap instead of asking pattern matching to do the impossible.",
    pillar: "build-securely",
    primaryCategory: "application-code-security",
    contentType: "guide",
    difficulty: "intermediate",
    status: "published",
    tags: ["secrets-management", "ci-cd-pipelines", "application-security"],
    audience: ["practitioner", "security-engineer"],
    estimatedReadingMinutes: 13,
    publishedAt: "2026-08-30",
    lastReviewedAt: "2026-08-30",
    updatedAt: "2026-08-30",
    labRequired: false,
    authorizedLabOnly: false,
    vendorNeutral: true,
    evidenceState: "UNVERIFIED",
    privacyReview: { status: "approved", reviewer: "Codex", reviewedAt: "2026-08-30" },
    technicalReview: { status: "approved", reviewer: "Codex", reviewedAt: "2026-08-30" },
    publicationApproval: { status: "approved", reviewer: "Ravi Teja Thota", reviewedAt: "2026-08-30" },
  },
  sections,
  module: module_,
  diagram,
};
