import type {Metadata} from "next";
import {Shell} from "@/components/site-shell";

export const metadata: Metadata = {
  title: "About",
  description: "Ravi Teja Thota — security engineer writing SecurityCorp. Background, certifications, and the evidence standard behind the publication.",
  alternates: {canonical: "/about"},
  openGraph: {type: "profile", url: "https://securitycorp.net/about", title: "About | SecurityCorp", description: "Ravi Teja Thota — security engineer writing SecurityCorp.", images: ["/opengraph-image"]},
  twitter: {card: "summary_large_image", title: "About | SecurityCorp", description: "Ravi Teja Thota — security engineer writing SecurityCorp."},
};

export default function About(){return <Shell current="/about"><main className="inner-page"><section className="page-intro about-intro grid-lines"><p className="section-label">Author profile</p><h1>Built by an engineer<br/>who likes <em>proof.</em></h1><p>I’m Ravi Teja Thota. I hold an MS in Cybersecurity Engineering and work across cloud, containers, and offensive testing — the stubborn operational details that decide whether a control holds up under pressure, not just whether it looks right in a diagram.</p></section><section className="about-grid"><div><p className="section-label">Why SecurityCorp</p><h2>Less theater.<br/>More evidence.</h2></div><div className="about-copy"><p>SecurityCorp exists to make security writing more useful than most of what gets published. That means the failed tests run alongside the clean architecture, an explanation of why a design was chosen over the alternatives, and a hard line between a plausible control and a verified one.</p><p>The lab behind these notes includes containerized services, private networking, malware scanning automation, reverse proxies, source control, storage systems, and a parity-first Kubernetes migration. Details that could expose the environment are generalized; the engineering lessons are not.</p><h3>Areas of practice</h3><ul><li>Kubernetes and container security</li><li>Detection engineering and automation</li><li>Secure self-hosting and network architecture</li><li>Cloud security and identity</li><li>Adversary-informed validation</li></ul></div><aside><p className="mono-label">CERTIFICATIONS</p><div className="cert-list"><span>CKA</span><span>CKS</span><span>CKAD</span><span>CRTP</span><span>AWS SAA</span><span>CySA+</span><span>Security+</span><span>Network+</span></div><p className="mono-label">CURRENT ROLE</p><p>Security Engineer</p></aside></section></main></Shell>}
