import Link from "next/link";
import type {Metadata} from "next";
import {ArrowRight,ArrowUpRight,CheckCircle2,CircleDot,BookOpen,ShieldCheck,FileCheck,Hourglass} from "lucide-react";
import {Shell} from "@/components/site-shell";
import {articles,projects} from "@/lib/content";
import {buildLog} from "@/lib/build-log";
import {controlScenarios} from "@/lib/control-under-test";
import {ControlUnderTest} from "@/components/control-under-test";
import {HeroVisual} from "@/components/hero-visual";
import {ProjectSchematic,type ProjectVisual} from "@/components/diagrams/project-schematic";
import {ogImages,twitterImages} from "@/lib/seo";
import {homepageCertifications} from "@/lib/profile";

const statusIcon = {published:BookOpen,validated:ShieldCheck,documented:FileCheck,planned:Hourglass} as const;
const statusLabel = {published:"Published",validated:"Validated",documented:"Documented",planned:"Planned"} as const;
const projectStatusIcon = {Validated:CheckCircle2,Operational:CheckCircle2,Design:CircleDot} as const;
const projectStatusClass = {Validated:"status-validated",Operational:"status-operational",Design:"status-design"} as const;
// Keyed by project index (stable identity), not status — the schematic
// choice must never be read as implying operational state.
const projectVisualByIndex: Record<string,ProjectVisual> = {"P-01":"file-intake","P-02":"vpn-tunnel","P-03":"gateway","P-04":"k8s-parity"};

export const metadata: Metadata = {
  title: "SecurityCorp — Security is a practice",
  description: "Hands-on security guides, honest lab notes, and defensive systems built to fail safely. Field notes from a practitioner, not a listicle.",
  alternates: {canonical: "/"},
  openGraph: {type: "website", url: "https://securitycorp.net", siteName: "SecurityCorp", title: "SecurityCorp — Security is a practice", description: "Hands-on security guides, honest lab notes, and defensive systems built to fail safely.", images: ogImages("SecurityCorp — Security is a practice")},
  twitter: {card: "summary_large_image", title: "SecurityCorp — Security is a practice", description: "Hands-on security guides, honest lab notes, and defensive systems built to fail safely.", images: twitterImages("SecurityCorp — Security is a practice")},
};

export default function Home(){return <Shell current="/"><main>
<section className="hero grid-lines"><div className="hero-kicker entrance" style={{"--d":"0ms"} as React.CSSProperties}><span className="hero-kicker-left"><span className="hero-tag">Field note // 001</span>Independent security field notes</span><span>Est. 2026</span></div><div className="hero-copy"><h1 className="entrance" style={{"--d":"70ms"} as React.CSSProperties}>Security is a<br/><em>practice.</em></h1><p className="entrance" style={{"--d":"140ms"} as React.CSSProperties}>Hands-on guides, honest lab notes, and defensive systems built to fail safely. Written for engineers, learners, and the relentlessly curious.</p><Link href="/guides" className="primary-link primary-link-terminal entrance" style={{"--d":"210ms"} as React.CSSProperties}>Explore the field notes <ArrowRight size={17} aria-hidden="true"/></Link></div><HeroVisual /><div className="scope-card clip-corner entrance" style={{"--d":"280ms"} as React.CSSProperties}><p className="mono-label">CURRENT SCOPE / 04</p><ul><li><span>01</span>Container & Kubernetes security</li><li><span>02</span>Detection engineering</li><li><span>03</span>Secure self-hosting</li><li><span>04</span>Cloud & identity</li></ul><div className="signal entrance" style={{"--d":"350ms"} as React.CSSProperties}><i/>Last documented state: {articles[0].date}</div></div></section>
<section className="manifesto"><p className="section-label">The premise</p><blockquote>Good security writing should show the <em>tradeoffs, failures,</em> and <em>evidence</em>—not just the final configuration.</blockquote><p>SecurityCorp documents real builds from the first threat model through the last regression test. Private details are removed; useful lessons stay intact.</p></section>
<section className="build-log"><p className="section-label">Publication activity</p><h2>Build log.</h2><p className="head-copy">A running record of what&apos;s been written, verified, and planned — not a live system feed.</p><div className="build-log-track" data-motion="once" data-motion-duration="2200"><div className="build-log-circuit-line" aria-hidden="true"/><ol>{buildLog.map((entry,i)=>{const Icon=statusIcon[entry.status];const content=<><span className={`build-log-icon build-log-icon-${entry.status} flow-pulse-once`} style={{"--pulse-delay":`${300+i*260}ms`} as React.CSSProperties}><Icon size={16} aria-hidden="true"/>{i===0&&<span className="build-log-ambient" aria-hidden="true"/>}</span><div><span className="build-log-date mono-label">{entry.date}</span><span className={`build-log-status build-log-status-${entry.status}`}>{statusLabel[entry.status]}</span><h3>{entry.title}</h3>{entry.summary&&<p>{entry.summary}</p>}</div></>;return <li key={entry.title} className="reveal">{entry.href?<Link href={entry.href} className="build-log-row">{content}</Link>:<div className="build-log-row">{content}</div>}</li>})}</ol></div></section>
<section className="latest"><div className="section-head"><div><p className="section-label">Latest intelligence</p><h2>Guides from the lab</h2></div><Link href="/guides">View all guides <ArrowUpRight size={15} aria-hidden="true"/></Link></div><div className="article-list">{articles.map(a=><Link href={`/guides/${a.slug}`} className="article-row record-trace" key={a.slug}><span className="article-no">{a.number}</span><div><div className="article-meta"><span>{a.category}</span><span>{a.read} read</span><span>{a.level}</span></div><h3>{a.title}</h3><p>{a.dek}</p></div><ArrowUpRight className="row-arrow" aria-hidden="true"/></Link>)}</div></section>
<ControlUnderTest scenarios={controlScenarios} />
<section className="projects-preview"><div className="section-head light"><div><p className="section-label">Selected builds</p><h2>Systems, not demos.</h2></div><p className="head-copy">Real infrastructure, instrumented and tested. Each project records its assumptions, controls, and known limitations.</p></div><div className="project-grid">{projects.map((p)=>{const StatusIcon=projectStatusIcon[p.status];return <article className="project-card record-trace clip-corner-sm" data-tilt key={p.index}><div className="project-top"><span>{p.index}</span><span className={`status ${projectStatusClass[p.status]}`}><StatusIcon size={12} aria-hidden="true"/> {p.status}</span></div><ProjectSchematic visual={projectVisualByIndex[p.index]} /><h3>{p.title}</h3><p>{p.text}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div>{p.slug?<Link href={`/projects/${p.slug}`} className="card-cta">View case study <ArrowUpRight size={13} aria-hidden="true"/></Link>:p.guideSlug?<Link href={`/guides/${p.guideSlug}`} className="card-cta">Read the guide <ArrowUpRight size={13} aria-hidden="true"/></Link>:null}</article>})}</div><Link href="/projects" className="outline-link">Open the project index <ArrowRight size={16} aria-hidden="true"/></Link></section>
<section className="author-strip"><div><p className="section-label">Your operator</p><h2>Ravi Teja Thota</h2><p>Writes SecurityCorp from the point where architecture diagrams meet inconvenient reality — Kubernetes, cloud, and detection engineering, tested before they&apos;re published.</p></div><div className="credentials">{homepageCertifications.map(c=><span key={c}>{c}</span>)}</div><Link href="/about" className="text-link">More about the author <ArrowRight size={15}/></Link></section>
</main></Shell>}
